// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJNOInEKbiwWuxRJpKPhjZ4SpgXLOJ-M',
    appId: '1:951109102209:android:b750de78694bc16844fb80',
    messagingSenderId: '951109102209',
    projectId: 'hedieatyproject',
    storageBucket: 'hedieatyproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBsR55dsO1-xt2kqgQuYl5PpYouj49Erk',
    appId: '1:951109102209:ios:e249b9d1023ddad744fb80',
    messagingSenderId: '951109102209',
    projectId: 'hedieatyproject',
    storageBucket: 'hedieatyproject.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmx8fRpC-_jQaEn-sQJBH8DcoLpDMJGM',
    appId: '1:951109102209:web:f630f59c0eb22cf444fb80',
    messagingSenderId: '951109102209',
    projectId: 'hedieatyproject',
    authDomain: 'hedieatyproject.firebaseapp.com',
    storageBucket: 'hedieatyproject.firebasestorage.app',
    measurementId: 'G-ETXCCW0JGR',
  );
}
